[package]
name = "hello-tokio"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mini-redis = "0.4.1"
rand = "0.8.4"
tokio = { version = "1.10.1", features = ["full"] }
